# Configuracion del Api Gateway
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: sport_management
            uri: lb://SMSCodersSport
            predicates:
              - Path=/api/v1/** #currently, we cannot have list of paths
              - Method=POST,PUT,GET,DELETE

management:
  endpoint:
    gateway:
      enabled: true

# Configuration of Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
