# Configuracion del Api Gateway
spring:
  application:
    name: sms-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: sport_management
            uri: lb://smsarchetype
            predicates:
              - Path=/teams/** #currently, we cannot have list of paths
              - Method=POST,PUT,GET,DELETE

# Actuator Activo
management:
  endpoint:
    gateway:
      enabled: true

# Configuracion de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
